### ISSUE TITLE
Race condition in vote function

### ISSUE THREAD

**Issue by Zagrebelin** [machinalis/mypy-django-example#2]
If someone do POST to vote function while another request is processing you will lose a vote.
I suggest to rewrite `vote` function with something  like this

`Choice.objects.filter(pk=request.POST['choice']).update(votes=F('votes')+1)`

**Comment by dmoisset** [comment]
Hi, thank you for your comment.

The purpose of this repo is to demonstrate the use of https://github.com/machinalis/mypy-django on a well known piece of code, namely the Django tutorial from https://docs.djangoproject.com/en/1.10/intro/tutorial01/ . The code you mention was just copied from https://docs.djangoproject.com/en/1.10/intro/tutorial04/#write-a-simple-form (where, at the end of that section, it actually mentions the problem you detected).

As this code is mostly for documentation purposes, it's more important for me that it's consistent with the official tutorial than its correctness (it's not supposed to be run in production)
